theme: minima
title: My space
author: Sowmya Kothurwar
email: sowmya.kothurwar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This Covid-19 has been a blessing in disguise that I was able to pursue my interest in Data through Artifical Intelligence. My journey began in mid March and today marks my first dat on GitHub

# social links
twitter_username: SKothurwar # DO NOT include the @ character, or else the build will fail!
github_username:  26skothurwar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
